### ISSUE TITLE
Minifier turns (0, eval) into eval

### ISSUE THREAD

**Issue by rdogmartin** [madskristensen/BundlerMinifier#63] opened 2015-10-08 20:29 UTC
When I minify jsViews.js (https://github.com/BorisMoore/jsviews), the resulting script fails. After digging in, I came up with a very small repro:

(function(factory) {
    factory();
}
(function () {
    "use strict";
    var global = (0, eval)('this');
    console.log(global); // Is undefined when run from the minified file
}));

The minifier produces this:

(function(n){n()})(function(){"use strict";var n=eval("this");console.log(n)});

The root cause is the minifier replacing (0, eval) with eval, because when I change it back it works. I also noticed that removing "use strict" eliminates the error.

Boris Moore, the creator of jsViews, suggests this is an issue with the minifier. He points to http://stackoverflow.com/a/14120023/1054484 which implies that (0, eval) and eval are not always equivalent.

**Comment by BorisMoore** [comment] 2015-10-11 18:39
I use uglify for minifying jsviews, for download: http://www.jsviews.com/download/jquery.views.min.js 

This code: 

```
var global = (0, eval)('this'), // jshint ignore:line
		$ = global.jQuery;
```

gets minified by Uglify to `var t=(0,eval)("this"),n=t.jQuery;`

and by VS minifier to: `var i=eval("this"),t=i.jQuery;`

If I use the VS minified version of jsviews.min.js on the  http://www.jsviews.com single page app, it fails, because  `(0,eval)("this")` is returning `window`, but `eval("this")` is returning undefined since the context is not the global context..

So yes - I think this is an important bug to fix.

**Comment by madskristensen** [comment] 2015-11-12 22:22
Please open a bug on the [AjaxMin](http://ajaxmin.codeplex.com/) repo

**Comment by rdogmartin** [comment] 2015-11-13 00:13
Done: https://ajaxmin.codeplex.com/workitem/22084

**Comment by rdogmartin** [comment] 2015-11-17 17:46
Unfortunately, it appears no one is maintaining Microsoft Ajax Minifier, leaving this bug just hanging out there. Bummer...

**Comment by madskristensen** [comment] 2015-11-18 23:41
If AjaxMin is no longer being maintained, perhaps I should use a different minifier. Any ideas for one that is good and still maintained?

**Comment by rdogmartin** [comment] 2015-11-19 02:02
Hi Mads,

I'm not really qualified to say, but I have great respect for Boris Moore
on his jsRender project, <https://github.com/BorisMoore/jsrender> and he
has said he uses the javascript-based uglify
<https://github.com/mishoo/UglifyJS2>. We know that properly compresses his
code. And a quick look at the GitHub site shows that it is active and
popular.

BTW, I always enjoy listening to you when you're on .NET Rocks.

Cheers,
Roger

**Comment by BorisMoore** [comment] 2015-11-19 04:10
Thanks, Roger, and Hello Mads...

Well I am also no expert on minifiers, but certainly Uglify seems to have a very good reputation. I use it partly because of using gulp-uglify - and it seems to be the minifier of choice for using with gulp...

So I would put in a vote for https://github.com/mishoo/UglifyJS2.

Boris

**Comment by 304NotModified** [comment] 2015-11-19 08:54
I think this issue isn't solved yet and should be reopened?

**Comment by kipusoep** [comment] 2016-01-20 11:58
Just ran into this issue when I tried to minify [JsRender](https://github.com/BorisMoore/jsrender), please switch to something else than AjaxMin, it's not reliable anymore.
I also used YuiCompressor instead of AjaxMin with SquishIt for these kind of reasons.

**Comment by BorisMoore** [comment] 2016-01-21 00:43
Yes - please could you go ahead and switch to Uglify, for example? Uglify also comes out slightly smaller than AjaxMin.

**Comment by 304NotModified** [comment] 2016-01-21 06:58
I think a PR would be accepted on this one?

**Comment by BorisMoore** [comment] 2016-01-21 07:12
Good, but I'm afraid I'm not in a position to take it on myself. (Working hard to complete documentation on JsViews and move to official V1.0)

**Comment by madskristensen** [comment] 2016-01-21 15:39
@304NotModified Yes, indeed. Is YUI compressor the best alternative to AjaxMin? Uglify doesn't run inside a C# process

**Comment by kipusoep** [comment] 2016-01-21 15:41
Last commit 29 Sep 2014 :-1:

**Comment by BorisMoore** [comment] 2016-02-04 17:57
People using JsRender are continuing to hit this issue. It really would be great to find a way to resolve it. 

About running Uglify in a C# process - I'm not sure what the reason is for not being able to do that. But given that Visual Studio has Grunt and Gulp integration - wouldn't running a Grunt or Gulp task using the corresponding Uglify plugin potentially provide a way in which (internally) VS can use Uglify for minifying?

**Comment by MisterY** [comment] 2016-02-05 11:37
+1

**Comment by shatl** [comment] 2016-02-06 16:05
+1

**Comment by BorisMoore** [comment] 2016-02-11 01:08
Hi Mads, 

Can you give a sense of what the status is for this? Looks like it's a choice of:

1. Find a way to use Uglify, (possibly by 'wrapping' in a Gulp or Grunt task).
2. Use another minifier - what would the alternatives be?
3. Stay with AjaxMin - but get a fixed version of it. Ron Logan no longer works for MS apparently, but is AjaxMin officially no longer maintained? Not sure where @rdogmartin found that out. Is there someone who has some knowledge of that code base who might provide a fix?  

Thanks!
Boris

**Comment by madskristensen** [comment] 2016-02-11 02:45
I haven't done any work on this. Running Uglify is not an option I want to pursue, due to adding additional moving parts (processes) into the mix has caused so much instability in my other extensions in the past. Moving over to YUI Compressor seems like the best solution, since AjaxMin is no longer maintained. Ron Logan confirmed that to me a couple of months ago.

**Comment by BorisMoore** [comment] 2016-02-11 08:09
OK, thanks, Mads, but still, I wonder it YUI Compressor will work as an ongoing minifier: It seems that YUI Compressor was deprecated. http://yuiblog.com/blog/2012/10/16/state-of-yui-compressor/.

Then Joey Smith  took over as new owner - http://yuiblog.com/blog/2013/01/24/yui-compressor-has-a-new-owner/ but there has been very little activity, and no new release since May 2013.

See also https://groups.google.com/forum/?fromgroups#!topic/yuicompressor/_AODsghvFzU

**Comment by 304NotModified** [comment] 2016-02-17 12:54
About this special case `"(0, eval)('this');"`, I'm curious what it does.

Ronlo replied also on https://ajaxmin.codeplex.com/workitem/22084 (13 nov), with the almost the same question, but never got a reply?

part of his reply:
>  I don't quite understand what the difference is. `eval("this")` resolves the identifier `"eval"` to the global method, and then calls it, passing in the string `"this"`. `(0,eval)("this")` will evaluate the expression first: zero, then resolve the identifier `"eval"` to the global function. The result will be the global function, which is then called with the argument `"this"`. I know it must be some sort of calling scope thing or something, but I'm just not seeing it.

if the TS can't reply on that, then I vote to close this issue.

**Comment by BorisMoore** [comment] 2016-02-17 18:13
`(0, eval)('this')` calls eval indirectly, and therefore it returns `this` evaluated in global scope - which is the `window` object, when run in a browser.

An indirect call to `eval` is when you first copy `eval` by reference, then call the copy:

    var myEval = eval;
    myEval('this');

for example. 

Using `(0,eval)('this')` is equivalent to the above: it returns a copy of `eval` by reference then calls it.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

So with this function:

```
function foo() {
  var globalThis = (0, eval)('this');
  var localThis = eval('this'); 
}
```

If you call `foo()` with "use strict" `localThis` is `undefined`.
If you call `foo.apply(myObject)` then `localThis` is `myObject`.
If you do `var myObject = {f: foo}; myObject.f();` then `localThis` is `myObject`.

In all those scenarios `eval('this')` is called in the local scope (the calling function context) but `(0, eval)('this')` calls `eval` in the global context, and `globalThis` is `window`. So semantically _the two are absolutely **NOT** equivalent_.

**Comment by BorisMoore** [comment] 2016-02-18 21:30
FYI https://github.com/BorisMoore/jsviews/issues/323#issuecomment-185930565

**Comment by madskristensen** [comment] 2016-06-16 18:14
The latest version 2.0 of the extension uses [NUglify](https://github.com/xoofx/NUglify) instead of AjaxMin. Please open the bug on their repo

**Closed by madskristensen** 2016-06-16 18:14 UTC

**Comment by BorisMoore** [comment] 2016-06-18 18:52
I linked back from a new issue: https://github.com/xoofx/NUglify/issues/7
