### ISSUE TITLE
Bundling is not performed when an input file is updated by another tool

### ISSUE THREAD

**Issue by heemskerkerik** [madskristensen/BundlerMinifier#35] opened 2015-08-19 09:11 UTC
The scenario is as follows: I have an `input.less` file which is compiled to an `input.css` file. That `input.css` file is the input for a bundle which outputs to `output.css`.

When I update `input.less` and save it, `input.css` file gets updated. `output.css`, however, does not get updated. When I open `input.css` and save it without changing anything, `output.css` is updated.

I'm not sure if this is, technically, an issue with Bundler & Minifier or with Web Compiler, but I assume the first, hence the issue here.

**Comment by madskristensen** [comment] 2015-08-19 16:59
You shouldn't need to use the `Bundler & Minifier` extension when dealing with LESS files. To do bundling, just create a .less file that contains a list of `@import` statements. That will compile them all as if they were bundled

**Comment by heemskerkerik** [comment] 2015-08-20 08:06
The issue we encounter is usually that you have a site.less file, which contains all of a site's custom CSS, and one or more external CSS files, like `datepicker.css` or `jquery.lightbox-0.5.css`. We'd like to bundle this, and having to introduce yet another .less file seems a sub-optimal solution.

Also, while that may be a solution for .less files, it's still an issue for, for example, CoffeeScript files that get compiled to JS. Especially when mixing languages, such as CoffeeScript and TypeScript.

Would watching for file changes be something you would want to consider?

**Comment by madskristensen** [comment] 2015-08-30 21:25
Yes, a FileSystemWatcher is required for this. Closing since it's a dupe of #28

**Closed by madskristensen** 2015-08-30 21:25 UTC
