### ISSUE TITLE
.css files not minified on save and can't force minification since 2.6.378

### ISSUE THREAD

**Issue by Link-69** [madskristensen/BundlerMinifier#352] opened 2018-04-13 14:12 UTC
### Installed product versions
- Visual Studio 2017 Enterprise 15.6.6
- This extension: 2.6.378

### Description
Hey, I've been using this awesome extension since we migrated from ASP.NET to ASP.NET Core and I'm now facing issues since the latest update (11/04/2018).
Now when I edit a file, the bundle output minified file isn't updated (bundle on save), only for .css files. Even when doing right click -> Re-bundle File, it won't bundle the minify version anymore.
Worse, I don't have option to minify a file when right-clicking on it, Bundle & Minifier menu is missing (.css and .js, except if it's a bundled file, with only the option to re bundle).

Extension is enabled of course. I tried nightly and it seems there's the same issue?

Any idea about why this could happen? Thanks!

**Comment by ikarydis** [comment] 2018-04-14 07:03
Same issue here. The update-on-save feature only starts working again if I open "bundleconfig.json" and save the file (without making a change).

**Comment by voicebooth** [comment] 2018-04-15 14:51
I'm experiencing the same issue, with the fix described by @ikarydis also working here - the bundleconfig.json file needs to be edited per visual studio session in order for things to start working.

**Comment by lepipele** [comment] 2018-04-16 02:53
This seems like duplicate of #351... let's continue discussion there. Close if you agree.

**Comment by lepipele** [comment] 2018-04-27 19:26
OK @Link-69 @ikarydis @voicebooth - moving this discussion to #351

**Closed by lepipele** 2018-04-27 19:26 UTC

**Comment by rockstardev** [comment] 2018-04-29 16:47
@Link-69 @ikarydis @voicebooth there seems to be solution for this: https://github.com/madskristensen/BundlerMinifier/issues/351#issuecomment-385259048
