### ISSUE TITLE
Bundle cascade usage

### ISSUE THREAD

**Issue by zecompadre** [madskristensen/BundlerMinifier#40] opened 2015-08-25 08:11 UTC
Sample:

bundleconfig.json file:

 [{
    "outputFileName": "ScriptsV2/test/ab.bundle.js",
    "inputFiles": [
      "ScriptsV2/test/b.js",
      "ScriptsV2/test/a.js"
    ],
    "minify": {
      "enabled": true
    },
    "includeInProject": true,
    "sourceMaps": false
  },
  {
    "outputFileName": "ScriptsV2/test/abc.bundle.js",
    "inputFiles": [
      "ScriptsV2/test/ab.bundle.js",
      "ScriptsV2/test/c.js"
    ],
    "minify": {
      "enabled": true
    },
    "includeInProject": true,
    "sourceMaps": false
  }]

files:

a.js
b.js
c.js

bundles:

ab.bundle.js -> add files a.js + b.js

abc.bundle.js -> add files ab.bundle.js + c.js

================
situation:

when updating file "a.js" the bundle "abc.bundle.js" don't update on save of file "a.js" and even on build, just update with Shift+Alt+I :(

any help ?

tks

**Comment by zecompadre** [comment] 2015-08-28 08:04
anyone can help ?

tks

**Comment by madskristensen** [comment] 2015-08-30 20:50
I can't reproduce the issue. Can you try the latest nightly and see if the issue has been fixed? http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

You might have to re-add the files to the `bundleconfig.json` file by using the context menu commands in Solution Explorer

**Comment by madskristensen** [comment] 2015-09-07 01:20
@zecompadre any update?

**Comment by zecompadre** [comment] 2015-09-08 15:30
still the same, if you put a bundle inside another just the first is updated on save :(

**Comment by madskristensen** [comment] 2015-09-08 15:58
What does `put a bundle inside another` mean?

**Comment by zecompadre** [comment] 2015-09-08 23:09
example:

1st bundle "abc.js"

contains the files:
a.js
b.js
c.js

2nd bundle "abcd.js"

contains the files:

d.js
abc.js (1st bundle)

if we change the file "a.js" 1st bundle, on save the bundle "abcd.js" is not updated.

It is only updated if we use the Shift+Alt+I shortcut

can you understand my explanation ?

Thanks

**Comment by zecompadre** [comment] 2015-09-22 09:25
@madskristensen any news ?

**Comment by madskristensen** [comment] 2015-09-22 16:26
Nope, just got back from vacation. I understand the issue now and it is a duplicate of #28. Until I implement `FileSystemWatcher` this can't be fixed

**Closed by madskristensen** 2015-09-22 16:26 UTC
