### ISSUE TITLE
CSS font file references are incorrectly changed during bundling and minification.

### ISSUE THREAD

**Issue by eat-sleep-code** [madskristensen/BundlerMinifier#248] opened 2017-03-16 16:36 UTC
### Installed product versions
- Visual Studio: [Professional 2015]
- This extension: [2.4.340]

### Description
CSS font file references are incorrectly changed during bundling and minification.

### Steps to recreate
1. Add reference to bootstrap using bower.
2. Create a bundle that uses the bootstrap.css as one of it's input files.
3. Set the output to be in wwwroot/css/site.min.css
4. Run bundling and minification.  
5. Inspect the output file.
6. Note that lines like: src: url('../fonts/glyphicons-halflings-regular.eot'); have been changed to url('../../bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot?');

### Current behavior
See above steps.   This is wrong because obviously you wouldn't  (or shouldn't) deploy the entire bower_components folder to your website.

### Expected behavior
Font references should be left in place, or there should be an option for it in the bundleconfig.json

**Comment by brannmar** [comment] 2017-05-19 08:41
@eat-sleep-code 
Duplicate of https://github.com/madskristensen/BundlerMinifier/issues/176

It is also solved in this one.

**Comment by richardwalker-iamtech** [comment] 2017-06-28 16:10
Hi,

I am using Visual Studio 2017 (version 15.2) with Bundler & Minifier 2.4.340.

I still have this problem: I have added bootstrap, and the Urls are not rewritten as you would expect.  The suggestions in issue 176 don't work for me.  Here's my CSS bundle:

{
    "outputFileName": "Bundles/app.css",
    "inputFiles": [
      "node_modules/bootstrap/dist/css/bootstrap-theme.css",
      "node_modules/bootstrap/dist/css/bootstrap.css"
    ],
    "minify": {
      "enabled": true,
      "adjustRelativePaths": false
    }

With the above config, my app.css (and app.min.css) file has:

    url('../fonts/glyphicons-halflings-regular.eot')

which is unchanged from the source (in node_modules/bootstrap/dist).

If I set 'adjustRelativePaths' to true and re-bunde, my app.css file looks like this:

    url('../node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.eot')

which is even less useful.  It has changed the URL, but to nonsense.  So I have the same problem as the OP.

How is this stuff supposed to work?  (I assume I'm doing something wrong!)

Also, what is the best approach for getting the font files themselves copied across?  I need them to be accessed locally via node_modules when running in visual studio, but when I publish my web site, I need them to be elsewhere (e.g. ~/fonts).  What tools do I need to use to achieve this?


Cheers,
Richard.

**Comment by ismcagdas** [comment] 2017-10-17 11:23
Hi,

I have the same case with @richardwalker-iamtech.
Will BundlerMinifier support such scenarios or should we use tools like gulp ?

**Comment by richardwalker-iamtech** [comment] 2017-10-17 11:59
For what it's worth, I eventually concluded that I should remove BundlerMinifier from my project.  I also don't want to explore tools like Gulp, as that's another item to try and integrate nicely into VS.

I've gone back to Microsoft's Web.Optimization Bundler and it 'just works'.  The only annoyance is that I have to publish the entire 'node_modules' and 'bower_components' directories along with my site (just a couple of settings in the project file).

I can't help thinking that the 'trendy way forward' (not so much with Mads' tools, but certainly the usual JS hipster crowd) with tools like gulp, is just hassle.  I don't see any real improvements.  Maybe I'm missing something?

**Comment by srd8580** [comment] 2017-12-19 18:18
I solved this by creating bundle objects for each font file required by Bootstrap.  I too, don't like going to Gulp unless it's absolutely necessary, because it just feels like too much overhead and setup time.  Hopefully this helps someone looking to keep their project build simple with this excellent tool!
```
{
    "outputFileName": "wwwroot/fonts/glyphicons-halflings-regular.woff",
    "inputFiles": [
      "wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
    ],    
    "minify": {
      "enabled": false,
      "renameLocals": false
    }
  },
```

**Closed** 2018-05-11 03:43 UTC
