### ISSUE TITLE
Cannot delete xxx.min.js file from projet?

### ISSUE THREAD

**Issue by ERICRAC** [madskristensen/BundlerMinifier#328] opened 2018-01-29 18:59 UTC
### Installed product versions
- Visual Studio: 2017
- This extension: 2.5.359

### Description
I can't delete minified file. The delete option is not available when minified file is selected. If I delete the file from the directory, the file is always attached to the project, declared as missing. If I delete the "mother" file from project and add again the "ghost" file is always here!!!
What is the meaning and how to reproduce "attached/children/dependent" file like .minified file with other file and VS options.

### Current behavior
I'm not able to delete minified file from project

### Expected behavior
I should be able to delete minified file from project

**Comment by Casimodo72** [comment] 2018-02-27 12:43
Not sure if this answers your question, because I can't reproduce your scenario "The delete option is not available when minified file is selected". I can always delete the minified file manually, but the file is of course regenerated after the next bundle update if you keep the default behavior.

In order to get rid of your minified file, or to be able to manually exclude it from the project:

1) Don't generate the minified file in the first place.
Use option "minify": https://github.com/madskristensen/BundlerMinifier/wiki/bundleconfig.json-specs#minify

2) Don't automatically include both files (the non-minified and the minified) in the project. This way both files will be generated but you can manually include what you want (i.e. only the non-minified file).
Use option "includeInProject": https://github.com/madskristensen/BundlerMinifier/wiki/bundleconfig.json-specs#includeinproject

**Comment by Roamel** [comment] 2018-04-11 17:08
@ERICRAC, just FYI, using version 2.6.378 I am able to delete minified version without any issues.

**Comment by lepipele** [comment] 2018-04-11 18:00
Hey @ERICRAC - I'm closing this in light of answers by @Casimodo72 and @Roamel, let me know if you need it reopened.

**Closed by lepipele** 2018-04-11 18:00 UTC
